### ISSUE TITLE
about use closehandle

### ISSUE THREAD

**Issue by Saxo0213** [yihleego/pywinhandle#1]
hello~when I use pywinhandle I can find handle about the name, than I close it,but I need to stop my all code ,its can be close,How can I solve this problem?

**Comment by yihleego** [comment]
Hi @Saxo0213,
I also encountered a problem similar to yours, you can try this: 

```python
def close():
    close_handle(123456, 1)
    close_handle(123456, 2)

if __name__ == '__main__':
    p = multiprocessing.Process(target=close)
    p.start()
    p.join()
    print('closed')
```

**Comment by Saxo0213** [comment]
I use tk.button to try it,

class M_process_del(mp.process):
    def run(self):
        try:
            PsID= py.find_handles(None,'name')
        except:
            pass
        if PsID==None:
            return
        for x in PsID:
            if 'name' in x['name']:
                py.close_handle(x['process_id'],x['handle'])
                print('closed')

def process_del():
    Pr=M_process_del()
    Pr.start()
    Pr.join()

**Comment by Saxo0213** [comment]
Thank you ,its can solve this problem,but not my hope. Because this prosses at the background need to find thread
I use tkinter to building my UI，New problem is the win will run*N....
Do  you find why does this problem happen?I mean close_handle

**Comment by yihleego** [comment]
Hello @Saxo0213, 
I fixed it, plz try closing handles without using `multiprocessing.Process`.
See  1fec959787287e64f8e1de8d3016838282774b5d
